add initial nyt scraper
ujjwal95/bloomberg_editorial_classifier pull request #1
Opened 2019-10-01 00:48 UTC by ujjwal95

I addad an initial New York Times scraper, it does not work on certain sections of the NYT website, such as the 'first draft' and 'watching' urls section of the website.

2019-10-01 03:25 UTC, ameyakarnad reviewed
Hi Ujjwal, 

Just a general couple of points. Others are invited to comment as well

-  I think you should put every thing in a folder. Lets start with a folder structure to ensure nothing is messy, and we get easier access to code ASAP. 
- I was thinking of adding a base directory structure with empty readme file.

--EDIT-- I created a branch with some basic structure, If everybody is fine with it, we could merge that first and create our "Data Extracters" files for different websites under it --/EDIT--

Let me know what you guys think about it

2019-10-01 03:51 UTC, ujjwal95 commented
Good point. I had forgotten about it, sorry. I made a new pull request for that, we can discuss it there.

2019-10-05 17:56 UTC, aastha99 approved these changes

2019-10-05 18:00 UTC, Nirali22 approved these changes

2019-10-05 18:22 UTC, ameyakarnad requested changes
Please Move these into the new directory Structure. We can push this immediately and continue working on the rest similar to the structure provided

2019-10-05 20:21 UTC, merged